  export class JobOffer{       
    id?: number;  //  Auto-generated by backend, so it's optional
    title:string | undefined;
          description:string | undefined;
          company:string | undefined;
          location:string | undefined;
          status:string | undefined;
          keywords!: string;
          remuneration!:number;
          type!:string;
        }
